version: '2'

services:

  ariadna:
    build:
      context: .
      dockerfile: Dockerfile-ariadna
    command: /go/bin/ariadna http
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./index.json:/go/src/github.com/maddevsio/ariadna/index.json
    depends_on:
      - ariadna-pg
      - ariadna-es
    environment:
      - ARIADNA_ES_INDEX_NAME=addresses
      - ARIADNA_INDEX_TYPE=address
      - ARIADNA_PG_CONN_URL=host=ariadna-pg user=ariadna password=ariadna dbname=ariadna sslmode=disable
      - ARIADNA_ES_HOST=http://ariadna-es:9200
      - ARIADNA_DOWNLOAD_URL=http://download.geofabrik.de/asia/kyrgyzstan-latest.osm.pbf
      - ARIADNA_FILE_NAME=kyrgyzstan-latest.osm.pbf
    networks:
      - ariadna-net

  ariadna-pg:
    image: kartoza/postgis:9.6-2.4
    volumes:
      - ./postgis.sql:/docker-entrypoint-initdb.d/postgis.sql
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=ariadna
      - POSTGRES_PASSWORD=ariadna
      - POSTGRES_DB=ariadna
    container_name: ariadna-pg
    networks:
      - ariadna-net

  ariadna-es:
    image: elasticsearch
    restart: always
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
    container_name: ariadna-es
    networks:
      - ariadna-net

volumes:
  esdata:
    driver: local
  pgdata:
    driver: local

networks:
  ariadna-net:
